#!/bin/bash
# hardkernel CloudShell Screen update
#
# requires the following packages:
# curl sysstat
#

############## Configuration

# Disable LCD Slepp mode
echo -e '\033[9;0]' > /dev/tty1

# console font
# More fonts on: /usr/share/consolefonts
export TERM="linux"
export CONSOLE_FONT="Lat7-Fixed18"
#export CONSOLE_FONT="Lat15-TerminusBold20x10"

# Output Console (ttyX)
export OUTPUT_CONSOLE="1"

# Network Interface: enx001e06323348, wlan0, ....
export NETIF=eth0

# Screen refresh in seconds
export REFRESH="1"

# CPU Temperature in C or F
export TEMPERATURE_FORMAT="C"

# External IP Refresh counts
# The time to update the ip in counts is acquired by using the following formula
# seconds_to_refresh = EXT_IP_REFRESH * REFRESH
export EXT_IP_REFRESH="10"

get_external_ip() {
	export EXTERNAL_IP=`/usr/bin/curl -s http://mdrjr.net/ip.php`
}

get_full_date() {
	export DATE=`date +"%Y-%m-%d %H:%M:%S"`
}

get_hostname() {
	export HOSTNAME=`hostname`
}

get_internal_ip() {
	export INTERNAL_IP=`ifconfig $NETIF | grep 'inet addr:'| cut -d: -f2 | awk '{ print $1}'`
}

get_net_tx_rx_realtime() {
	net_txrx=`sar -n DEV 1 1 | grep $NETIF | tail -n 1 | gawk '{print $5" "$6}'`
	# in MB/s
	_tx=`echo $net_txrx | awk '{printf $1}'`
	_rx=`echo $net_txrx | awk '{printf $2}'`
	export NET_TX=`echo "scale=1; x=$_tx/1024; if(x<1) print 0; x" | bc`
	export NET_RX=`echo "scale=1; x=$_rx/1024; if(x<1) print 0; x" | bc`
	
}

get_disk_mount_info() {
	IFS=$'\n' SATA=(`mount | grep "/dev/sd" | awk '{ print $1 }'`)
	export mountedNum=`mount | grep "/dev/sd" | awk '{ print $1 }' | wc -l`
	if [ $mountedNum -ge 2 ]
	then
		mountedNum=2
	fi
}

get_disk_info() {
	for (( i=0; i<=$mountedNum-1; i++))
	do
		t=`df -h | grep ${SATA[$i]}`
		export DISK_SIZE$i=`echo $t | awk '{printf $2}'`
		export DISK_USED$i=`echo $t | awk '{printf $3}'`
		export DISK_FREE$i=`echo $t | awk '{printf $4}'`
		export DISK_USED_PCT$i=`echo $t | awk '{printf $5}'`
		SAT=`expr "${SATA[$i]#"/dev/"}" : '\([a-z]*\)'`
		
		export DISK_R$i=`iostat -m 1 2 | grep $SAT | awk 'FNR == 2 {print $3}'`
		export DISK_W$i=`iostat -m 1 2 | grep $SAT | awk 'FNR == 2 {print $4}'`
	done
}

get_disk_temperature() {
	smart=`smartctl -d sat /dev/sda -a | grep "SMART support is: Avail"`
	if [ "$smart" ]
	then
		for (( i=0; i<=$mountedNum-1; i++))
		do
			t=`smartctl -a ${SATA[$i]} -d sat | grep Temp`
			TEMP=`echo $t | awk '{printf $10}'`
			export DISK_TEMP$i=" Temp: $TEMP$TEMPERATURE_FORMAT"
		done
	else
		export DISK_TEMP$i=""
	fi
}

get_memory_info() {
	# in Mbytes
	export MEM_FREE=$[`cat /proc/meminfo | grep MemFree | awk '{print $2'}` / 1024]
	export MEM_TOTAL=$[`cat /proc/meminfo | grep MemTotal | awk '{print $2'}` / 1024]
	export MEM_USED=$[$MEM_TOTAL - $MEM_FREE]
}

get_system_info() {
	export UBUNTU_VERSION=`lsb_release -r | awk '{print $2'}`
	export KERNEL_VERSION=`uname -r | awk '{print substr($1,0,6)}'`
}

get_cpu_usage() { 
	cpufree=`mpstat 1 1 | tail -n 1 | awk '{printf $12}'`
	export CPU_USAGE=`echo "scale=1; x=100-$cpufree; if(x<1) print 0; x" | bc`
}

get_cpu_temperature() {
	_t=$[`cat /sys/class/thermal/thermal_zone0/temp` / 1000]
	if [ "$TEMPERATURE_FORMAT" = "C" ]; then
		export CPU_TEMP="$_t"C
	else
		_t1=$[ $_t * 9 / 5 + 32 ]
		export CPU_TEMP="$_t1"F
	fi
}

get_samba_connections() {
	if [ ! -f /usr/bin/smbstatus ]; then
		export SAMBA_CONNECTIONS=0
	else
		export SAMBA_CONNECTIONS=`smbstatus -b | grep -c ipv`
	fi
}

get_nfs_connections() { 
	export NFS_CONNECTIONS=`netstat -an | grep 2049 | grep -c ESTA`
}

get_process_count() { 
	export PROCESS_COUNT=`ps xa | wc -l`
}

# local variables
ext_ip_refresh_c=0
COFF=$(tput sgr0)
CGREEN=$(tput setaf 2)
CRED=$(tput setaf 1)
CBLUE=$(tput setaf 6)
oc="/dev/tty$OUTPUT_CONSOLE"

# font setup
setfont $CONSOLE_FONT > $oc

# Ensure that we are in the right TTY
chvt $OUTPUT_CONSOLE

# infinite loop
while true; do

	# Ensure that we are in the right TTY
	chvt $OUTPUT_CONSOLE

	# check if EXT_IP_REFRESH
	if (( ($ext_ip_refresh_c % $EXT_IP_REFRESH) == 0 )); then
		get_external_ip
	fi
	
	# increment $ext_ip_refresh_c
	ext_ip_refresh_c=$[$ext_ip_refresh_c+1]

	# get data
	get_internal_ip
	get_hostname
	get_disk_mount_info
	get_disk_info
	get_disk_temperature
	get_full_date
	#get_net_tx_rx_realtime
	#get_memory_info
	get_system_info
	get_cpu_usage
	get_cpu_temperature
	#get_samba_connections
	#get_nfs_connections
    	get_process_count
    	
	# clear the screen every loop
	# we only wipe the screen when we are ready to write data to it
	clear > $oc

	# format the data on screen
	#echo "" > $oc
	echo -e "$CBLUE$HOSTNAME $COFF: $DATE" > $oc
    #echo "" > $oc
	echo -e "Ubuntu $CGREEN$UBUNTU_VERSION$COFF       Kernel $CGREEN$KERNEL_VERSION$COFF" > $oc
	# line CPU Usage
	echo -e "CPU Usage: $CBLUE$CPU_USAGE%$COFF  CPU Temp: $CRED$CPU_TEMP$COFF" > $oc
    # Line Memory
    #echo -e "Memory Free: $CBLUE$MEM_FREE MB$COFF   Used: $CBLUE$MEM_USED MB$COFF" > $oc
	# Line IP Addresses
	#echo -e "IP: $CBLUE$INTERNAL_IP$COFF Ext IP: $CBLUE$EXTERNAL_IP$COFF" > $oc
	echo -e "IP: $CBLUE$INTERNAL_IP$COFF" > $oc
	# Line network usage
	#echo -e "TX: $CBLUE$NET_TX MB/s$COFF RX: $CBLUE$NET_RX MB/s$COFF" > $oc
	# Line Disk Space

	
	for (( i=0; i<=$mountedNum-1; i++))
	do
		eval DISK_TEMP=\$$"DISK_TEMP$i"
		eval DISK_USED=\$$"DISK_USED$i"
		eval DISK_USED_PCT=\$$"DISK_USED_PCT$i"
		eval DISK_FREE=\$$"DISK_FREE$i"
		eval DISK_R=\$$"DISK_R$i"
		eval DISK_W=\$$"DISK_W$i"
		echo "" > $oc
		echo -e "${SATA[$i]} $CRED$DISK_TEMP$COFF" > $oc
		echo -e "R/W $CBLUE$DISK_R$COFF / $CBLUE$DISK_W$COFF MB/s" > $oc
		echo -e "Disk Used: $CBLUE$DISK_USED$COFF ($CBLUE$DISK_USED_PCT$COFF)  Free: $CBLUE$DISK_FREE$COFF" > $oc
	done

    # Line Samba
    #echo -e "Samba Clients: $CBLUE$SAMBA_CONNECTIONS$COFF" > $oc
    # line NFS
    #echo -e "NFS Connections: $CBLUE$NFS_CONNECTIONS$COFF" > $oc
	# line Processes

	# sleep
	sleep $REFRESH

done
